const { rankCheck, shouldUseEmbeds } = require('../../modules/functions');

module.exports = {
    name: 'generateinvite',
    description: 'Generate Invite.',
    async execute(message, args, bot) {
        const embed = shouldUseEmbeds(message.author.id);
        if(!rankCheck(message.author.id, 'support')) {
            if(embed) {
                return message.channel.send({
                    embed: {
                        title: 'Insufficient Permissions',
                        description: 'You have insufficient permissions to generate in invite link. This command is for bot support staff only.',
                    },
                });
            }
            return message.channel.send('**Insufficient Permissions**\nYou have insufficient permissions to generate in invite link. This command is for bot support staff only.');
        }

        const guild = bot.guilds.resolve(args[0]);
        if(!guild) {
            if(embed) {
                return message.channel.send({
                    embed: {
                        title: 'Guild couldn\'t be resolved',
                        description: `The guild you requested \`${args[0]}\` could not be resolved.`,
                        timestamp: new Date(),
                        footer: {
                            text: `Requested by ${message.author.tag} | Requested at `,
                            icon_url: message.author.displayAvatarURL(),
                        },
                    },
                });
            }
            return message.channel.send(`**Guild couldn't be resolved**\nThe guild you requested \`${args[0]}\` could not be resolved.`);
        }
        const channel = guild.channels.cache.find(chan => chan.type === 'text');
        if(!channel) {
            if(embed) {
                return message.channel.send({
                    embed: {
                        title: 'Guild Channel couldn\'t be resolved',
                        description: 'No channel was cached.',
                        timestamp: new Date(),
                        footer: {
                            text: `Requested by ${message.author.tag} | Requested at `,
                            icon_url: message.author.displayAvatarURL(),
                        },
                    },
                });
            }
            return message.channel.send('**Guild Channel couldn\'t be resolved**\nNo channel was cached.');
        }

        const invite = await channel.createInvite({
            maxAge: 60,
            maxUses: 1,
            unique: true,
            reason: `This invite was generated by ${message.author.tag}, a member of the SecuroBot support team.`,
        });
        if(!invite) {
            if(embed) {
                return message.channel.send({
                    embed: {
                        title: 'Invite could not be generated',
                        description: 'The invite link could not be generated, likely a lack of permissions.',
                        timestamp: new Date(),
                        footer: {
                            text: `Requested by ${message.author.tag} | Requested at `,
                            icon_url: message.author.displayAvatarURL(),
                        },
                    },
                });
            }
            return message.channel.send('**Invite could not be generated**\nThe invite link could not be generated, likely a lack of permissions.');
        }

        if(embed) {
            return message.channel.send({
                embed: {
                    title: 'Support Link',
                    description: `You generated an invite link for **${guild.name}** (${guild.id}).\nYou can join this guild by clicking [here](${invite.toString()}).`,
                    timestamp: new Date(),
                    footer: {
                        text: `Requested by ${message.author.tag} | Requested at `,
                        icon_url: message.author.displayAvatarURL(),
                    },
                },
            });
        }
        return message.channel.send(`**Support Link**\nYou generated an invite link for **${guild.name}** (${guild.id}).\nYou can join this guild by clicking this link, <${invite.toString()}>.`);
    },
};

